[package]
name = "warkov"
version = "0.1.0"
authors = ["Rory McCann <rory@technomancy.org>"]
license = "AGPL-3.0+"
repository = "https://github.com/rory/warkov"
description = "Use markov-chains to generate new items"
edition = "2021"

[dependencies]
rand = "0.5"
